# Generated by Django 4.2.4 on 2023-08-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='content_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
